const countries = {
  "en-US": "America",
  "en-GB": "English",
  "en-CA": "Canada",
  "en-AU": "Australia",
  "en-IN": "India",
  "zh-CN": "China",
  "zh-TW": "Taiwan",
  "zh-HK": "Hong Kong",
  "ja-JP": "Japan",
  "ko-KR": "South Korea",
  "fr-FR": "France",
  "fr-CA": "Canada (French)",
  "de-DE": "Germany",
  "es-ES": "Spain",
  "es-MX": "Mexico",
  "pt-PT": "Portugal",
  "pt-BR": "Brazil",
  "it-IT": "Italy",
  "ru-RU": "Russia",
  "ar-SA": "Saudi Arabia",
  "nl-NL": "Netherlands",
  "tr-TR": "Turkey",
  "vi-VN": "Vietnam",
  "th-TH": "Thailand",
  "id-ID": "Indonesia",
  "ms-MY": "Malaysia",
  "pl-PL": "Poland",
  "sv-SE": "Sweden",
  "no-NO": "Norway",
  "fi-FI": "Finland",
  "da-DK": "Denmark",
  "cs-CZ": "Czech Republic",
  "hu-HU": "Hungary",
  "he-IL": "Israel",
  "ro-RO": "Romania",
  "sk-SK": "Slovakia",
  "uk-UA": "Ukraine",
  "el-GR": "Greece"
};